sudo: false
language: node_js
node_js:
- "0.10"

before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16 -extension RANDR"
- npm install -g npm
- npm --version

before_script:
- npm install 
- npm install mozilla-download -g
- cd ..
- mozilla-download --branch FIREFOX_39_0 --product firefox $TRAVIS_BUILD_DIR/../
- cd $TRAVIS_BUILD_DIR

script:
- export JPM_FIREFOX_BINARY=$TRAVIS_BUILD_DIR/../firefox/firefox
- export FIREFOX_BIN=$JPM_FIREFOX_BINARY
- npm run test 
